/**
 * @file Contains all the action types needed for interacting with the redux store
 * @author Jonathan Weatherspoon
 */

export const INCREMENT_SCORE = 'INCREMENT_SCORE';
export const RESET_SCORE = 'RESET_SCORE';
export const UPDATE_HIGH_SCORE = 'UPDATE_HIGH_SCORE';
export const UPDATE_DIFFICULTY = 'UPDATE_DIFFICULTY';
export const INCREMENT_GAME_TIME = 'INCREMENT_GAME_TIME';
export const RESET_GAME_VARS = 'RESET_GAME_VARS';

export const UPDATE_SCREEN = 'UPDATE_SCREEN';

export const UPDATE_PLAYER_POSITION = 'UPDATE_PLAYER_POSITION';
export const INCREMENT_PLAYER_LIVES = 'INCREMENT_PLAYER_LIVES';
export const DECREMENT_PLAYER_LIVES = 'DECREMENT_PLAYER_LIVES';
export const UPDATE_PLAYER_CURRENCY = 'UPDATE_PLAYER_CURRENCY';
export const SET_PLAYER_CURRENCY = 'SET_PLAYER_CURRENCY';
export const INCREMENT_PLAYER_CURRENCY = 'INCREMENT_PLAYER_CURRENCY';
export const RESET_PLAYER = 'RESET_PLAYER';

export const UPDATE_PILLAR_POSITION = 'UPDATE_PILLAR_POSITION';
export const ACTIVATE_PILLAR = 'ACTIVATE_PILLAR';
export const DEACTIVATE_PILLAR = 'DEACTIVATE_PILLAR';
export const RESET_PILLARS = 'RESET_PILLARS';
// export const UPDATE_PLAYER_INVENTORY = 'UPDATE_PLAYER_INVENTORY';